version: '3'
services:
  db:
    restart: always
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: localdb
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - study-graphql-network

  # backend(Go GraphQL Server)
  backend:
    build: .
    ports:
    - "80:5050"
    networks:
      - study-graphql-network

  # frontend(Next.js app)コンテナを追加
  frontend:
    image: node:16-alpine
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - ./frontend/graphql:/usr/src/app
    command: sh -c "npm install && npm run dev"

volumes:
  localdb:
    external: false

networks:
  study-graphql-network:
    external: true