// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
}
